### ISSUE TITLE
Tags for a post do not show correctly on home page

### ISSUE THREAD

**Issue by CorinnaPhillips** [InspiringLifeDesign/InspiringLifeDesign.github.io#1]

**Comment by CorinnaPhillips** [comment]
The tags appear to be hard coded as tag 1, tag 2 & long tag 3, instead of the tags actually used on the post - for example on the first post the tags are 2017, First Post, About Corinna, Freedom Plan

**Comment by CorinnaPhillips** [comment]
The tags are now mostly working, but the year is showing twice for some reason.

**Comment by DavidForster** [comment]
Categories replaced with tags, which do not show this effect (integer based categories appear twice)
